// Copyright 2013-2026 Erudika. https://erudika.com
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// For issues and patches go to: https://github.com/erudika

import Foundation

/**
The core domain class. All Para objects extend it.
*/
open class ParaObject : NSObject {

	/// The id of an object. Usually an autogenerated unique string of numbers.
	open var id: String
	/// The time when the object was created, in milliseconds (Java-style Unix timestamp).
	open var timestamp: NSNumber?
	/// The type of the object.
	open var type: String
	/// The type in plural form
	open var plural: String
	/// The application name. Added to support multiple separate apps.
	/// Every object must belong to an app.
	open var appid: String
	/// The id of the parent object.
	open var parentid: String
	/// The id of the user who created this. Should point to a {@link User} id.
	open var creatorid: String
	/// The last time this object was updated. Timestamp in milliseconds.
	open var updated: NSNumber?
	/// The name of the object. Can be anything.
	open var name: String
	/// The tags associated with this object. Tags must not be null or empty.
	open var tags: [String]
	/// Returns the total sum of all votes for this object (score, weight etc.).
	open var votes: Int = 0
	/// Returns the version of this object.
	open var version: Int = 0
	/// Gets or sets a value indicating whether this object must be stored in DB.
	open var stored: Bool
	/// Gets or sets a value indicating whether this object must be indexed.
	open var indexed: Bool
	/// Gets or sets a value indicating whether this object must be cached.
	open var cached: Bool

	open var properties: [String: Any] = [:]


	public convenience override init () {
		self.init(id: "")
	}

	public convenience init (id: String) {
		self.init(id: id, type: "sysprop")
	}

	public init (id: String, type: String) {
		self.id = id
		self.type = type
		self.votes = 0
		self.version = 0
		self.name = "ParaObject"
		self.stored = true
		self.indexed = true
		self.cached = true
		self.plural = ""
		self.parentid = ""
		self.creatorid = ""
		self.appid = ""
		self.tags = []
	}

	/**
	The URI of this object. For example: /users/123.
	- returns: the URI string
	*/
	open func getObjectURI() -> String {
		let def = "/" + Signer.encodeURIComponent(self.type)
		return !self.id.isEmpty ? def + "/" + Signer.encodeURIComponent(self.id) : def
	}

	open func setObjectURI(_: String) { }

	subscript(name: String) -> Any {
		get {
			if let prop = self.properties[name] {
				return prop
			}
			return coreFieldValue(named: name) ?? NSNull()
		}
		set {
			if !assignCoreField(named: name, value: newValue) {
				self.properties[name] = newValue
			}
		}
	}

	/**
	Populates this object with data from a Dictionary.
	- parameter map: a dictionary of data
	*/
	open func setFields(_ map: [String: Any]? = [:]) {
		for (key, val) in map! {
			self[key] = val
		}
	}

    /**
     Returns a dictionary of fields and values.
     - returns: a dictionary of data
     */
    open func getFields() -> [String: Any] {
        if self.plural.isEmpty {
            self.plural = self.type
        }
        var props = [String: Any]()
        let mirror = Mirror(reflecting: self)


        var allChidren: [Mirror.Child] = []

        // childrens of superclass:
        if let superMirror = mirror.superclassMirror {
            for child in superMirror.children {
                allChidren.append(child)
            }
        }

        // childrens of this instance:
        for child in mirror.children {
            allChidren.append(child)
        }

        // now process them

        for child in allChidren {
            if let key = child.label {
                if key != "properties" {
                    if let po = child.value as? ParaObject {
                        props[key] = po.getFields()
                    } else {
                        let value:Any = child.value
                        let anyMirror = Mirror(reflecting: value)
                        if anyMirror.displayStyle == .optional {
                            if anyMirror.children.count > 0 {
                                let (_, unwrapped) = anyMirror.children.first!
                                props[key] = unwrapped
                            }
                        } else {
                            props[key] = value
                        }
                    }
                }
            }
        }
        for (key, val) in properties {
            props[key] = val
        }
        return props
    }

	private func coreFieldValue(named name: String) -> Any? {
		switch name {
			case "id": return self.id
			case "timestamp": return self.timestamp
			case "type": return self.type
			case "plural": return self.plural
			case "appid": return self.appid
			case "parentid": return self.parentid
			case "creatorid": return self.creatorid
			case "updated": return self.updated
			case "name": return self.name
			case "tags": return self.tags
			case "votes": return self.votes
			case "version": return self.version
			case "stored": return self.stored
			case "indexed": return self.indexed
			case "cached": return self.cached
			default: return nil
		}
	}

	@discardableResult
	private func assignCoreField(named name: String, value: Any) -> Bool {
		if value is NSNull {
			switch name {
				case "timestamp":
					self.timestamp = nil
					return true
				case "updated":
					self.updated = nil
					return true
				case "tags":
					self.tags = []
					return true
				default:
					return false
			}
		}
		switch name {
			case "id":
				if let string = asString(value) { self.id = string; return true }
			case "timestamp":
				if let number = asNumber(value) { self.timestamp = number; return true }
			case "type":
				if let string = asString(value) { self.type = string; return true }
			case "plural":
				if let string = asString(value) { self.plural = string; return true }
			case "appid":
				if let string = asString(value) { self.appid = string; return true }
			case "parentid":
				if let string = asString(value) { self.parentid = string; return true }
			case "creatorid":
				if let string = asString(value) { self.creatorid = string; return true }
			case "updated":
				if let number = asNumber(value) { self.updated = number; return true }
			case "name":
				if let string = asString(value) { self.name = string; return true }
			case "tags":
				if let list = asStringArray(value) { self.tags = list; return true }
			case "votes":
				if let intValue = asInt(value) { self.votes = intValue; return true }
			case "version":
				if let intValue = asInt(value) { self.version = intValue; return true }
			case "stored":
				if let boolValue = asBool(value) { self.stored = boolValue; return true }
			case "indexed":
				if let boolValue = asBool(value) { self.indexed = boolValue; return true }
			case "cached":
				if let boolValue = asBool(value) { self.cached = boolValue; return true }
			default:
				break
		}
		return false
	}

	private func asString(_ value: Any) -> String? {
		if let string = value as? String {
			return string
		}
		if let number = value as? NSNumber {
			return number.stringValue
		}
		return nil
	}

	private func asNumber(_ value: Any) -> NSNumber? {
		if let number = value as? NSNumber {
			return number
		}
		if let intValue = value as? Int {
			return NSNumber(value: intValue)
		}
		if let doubleValue = value as? Double {
			return NSNumber(value: doubleValue)
		}
		if let string = value as? String {
			if let intValue = Int(string) {
				return NSNumber(value: intValue)
			}
			if let doubleValue = Double(string) {
				return NSNumber(value: doubleValue)
			}
		}
		return nil
	}

	private func asInt(_ value: Any) -> Int? {
		if let intValue = value as? Int {
			return intValue
		}
		if let number = value as? NSNumber {
			return number.intValue
		}
		if let string = value as? String {
			return Int(string)
		}
		return nil
	}

	private func asBool(_ value: Any) -> Bool? {
		if let boolValue = value as? Bool {
			return boolValue
		}
		if let number = value as? NSNumber {
			return number.boolValue
		}
		if let string = value as? String {
			switch string.lowercased() {
				case "true", "1", "yes": return true
				case "false", "0", "no": return false
				default: return nil
			}
		}
		return nil
	}

	private func asStringArray(_ value: Any) -> [String]? {
		if let list = value as? [String] {
			return list
		}
		if let list = value as? [Any] {
			let strings = list.compactMap { $0 as? String }
			return strings.isEmpty ? nil : strings
		}
		if let string = value as? String {
			return [string]
		}
		return nil
	}

	/// Returns the JSON serialization of this object.
	open func toJSON() -> JSON {
		return JSON(getFields())
	}

	/// Returns the JSON string of this object.
	open override var description: String {
		return self.toJSON().rawString() ?? "{}"
	}
}
