// Copyright 2013-2016 Erudika. http://erudika.com
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// For issues and patches go to: https://github.com/erudika

import Foundation
import SwiftyJSON

/**
The core domain class. All Para objects extend it.
*/
public class ParaObject : NSObject {

	/// The id of an object. Usually an autogenerated unique string of numbers.
	public var id: String
	/// The time when the object was created, in milliseconds (Java-style Unix timestamp).
	public var timestamp: NSNumber?
	/// The type of the object.
	public var type: String
	/// The type in plural form
	public var plural: String
	/// The application name. Added to support multiple separate apps.
	/// Every object must belong to an app.
	public var appid: String
	/// The id of the parent object.
	public var parentid: String
	/// The id of the user who created this. Should point to a {@link User} id.
	public var creatorid: String
	/// The last time this object was updated. Timestamp in milliseconds.
	public var updated: NSNumber?
	/// The name of the object. Can be anything.
	public var name: String
	/// The tags associated with this object. Tags must not be null or empty.
	public var tags: [String]
	/// Returns the total sum of all votes for this object (score, weight etc.).
	public var votes: Int = 0
	/// Gets or sets a value indicating whether this object must be stored in DB.
	public var stored: Bool
	/// Gets or sets a value indicating whether this object must be indexed.
	public var indexed: Bool
	/// Gets or sets a value indicating whether this object must be cached.
	public var cached: Bool

	public var properties: [String: Any] = [:]

	private static var _coreFields: [String: AnyObject?]?

	public convenience override init () {
		self.init(id: "")
	}

	public convenience init (id: String) {
		self.init(id: id, type: "sysprop")
	}

	public init (id: String, type: String) {
		self.id = id
		self.type = (type ?? "sysprop")
		self.votes = 0
		self.name = "ParaObject"
		self.stored = true
		self.indexed = true
		self.cached = true
		self.plural = ""
		self.parentid = ""
		self.creatorid = ""
		self.appid = ""
		self.tags = []
	}
	
	/**
	The plural name of the object. For example: user -> users.
	- returns: a string
	*/
	public final func getPlural() -> String {
		if !(self.plural ?? "").isEmpty {
			return self.plural
		}
		if self.type.isEmpty || self.type.characters.count < 2 {
			self.type = "sysprop"
		}
		let last = self.type.substringFromIndex(self.type.endIndex.advancedBy(-1))
		let lastStripped = self.type.substringToIndex(self.type.endIndex.advancedBy(-1))
		return (self.type.isEmpty ? self.type :
			(last == "s" ? self.type + "es" :
			(last == "y") ? lastStripped + "ies" : self.type + "s"))
	}
	
	/**
	The URI of this object. For example: /users/123.
	- returns: the URI string
	*/
	public func getObjectURI() -> String {
		let def = "/" + getPlural()
		return !self.id.isEmpty ? def + "/" + self.id : def
	}
	
	public func setObjectURI(_: String) { }
	
	subscript(name: String) -> Any {
		get {
			return self.properties[name] ?? self.valueForKey(name)
		}
		set {
			if self.valueForKey(name) == nil && !ParaObject.getCoreFields().keys.contains(name) {
				self.properties[name] = newValue
			} else {
				self.setValue(newValue as? AnyObject, forKey: name)
			}
		}
	}
	
	public override func valueForUndefinedKey(key: String) -> AnyObject? {
		return nil
	}
	
	/**
	Populates this object with data from a Dictionary.
	- parameter map: a dictionary of data
	*/
	public func setFields(map: [String: AnyObject]? = [:]) {
		for (key, val) in map! {
			self[key] = val
		}
	}
	
	/**
	Returns a dictionary of fields and values.
	- returns: a dictionary of data
	*/
	public func getFields() -> [String: AnyObject] {
		if self.plural.isEmpty {
			self.plural = getPlural()
		}
		var props = [String: AnyObject]()
		let mirror = Mirror(reflecting: self)
		for child in mirror.children {
			if let key = child.label {
				if key != "properties" {
					if let po = child.value as? ParaObject {
						props[key] = po.getFields()
					} else {
						props[key] = child.value as? AnyObject
					}
				}
			}
		}
		for (key, val) in properties {
			props[key] = val as? AnyObject
		}
		return props
	}
	
	private static func getCoreFields() -> [String: AnyObject?] {
		if ParaObject._coreFields == nil {
			ParaObject._coreFields = [String: AnyObject?]()
			for child in Mirror(reflecting: ParaObject()).children {
				if let key = child.label {
					if key != "properties" {
						ParaObject._coreFields![key] = child.value as? AnyObject
					}
				}
			}
		}
		return ParaObject._coreFields!
	}

	/// Returns the JSON serialization of this object.
	public func toJSON() -> JSON {
		return JSON(getFields())
	}
	
	/// Returns the JSON string of this object.
	public override var description: String {
		return self.toJSON().rawString() ?? "{}"
	}
}